[build-system]
requires = ['setuptools', 'setuptools-scm', 'numpy', 'Cython']
# 'setuptools-scm' enables that any file tracked by git will be included in the installed package, thus enabling the inclusion of e.g. text files with data
build-backend = 'setuptools.build_meta'

[project]
name = 'NEoST'
authors = [{name = 'NEoST core team', email='A.L.Watts@uva.nl'}]
version = '2.1.0'
dependencies = ['numpy', 'scipy', 'matplotlib', 'numba', 'seaborn', 'corner', 'pymultinest', 'pytest', 'kalepy', 'jupyter', 'mpi4py']
license = {file = 'LICENCE'}
description = 'NEoST: An open-source code for dense matter equation of state inference via nested sampling.'
readme = 'README.md'
classifiers = ['Intended Audience :: Science/Research',
              'Operating System :: Mac OS X, Linux',
              'License :: OSI Approved :: GNU GPLv3 License',
              'Programming Language :: Python']

[tool.setuptools]
packages = ['neost', 'neost.eos', 'neost.tovsolvers']
